In [3]:
import pandas as pd

df = pd.read_json(r"D:\Data-science\panda\File\actors.json")
df

,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df['Actor'] # Read column

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [5]:
print(df['Actor'][0])

Shah Rukh Khan

In [6]:
type(df['Actor'])

pandas.core.series.Series

In [7]:
df[['Actor', 'IMDb_Rating']]

                 Actor  IMDb_Rating
0       Shah Rukh Khan          7.2
1          Salman Khan          6.0
2           Aamir Khan          8.4
3        Ranbir Kapoor          5.6
4        Ranveer Singh          7.0
5   Ayushmann Khurrana          8.3
6        Rajkummar Rao          7.5
7       Hrithik Roshan          6.5
8         Akshay Kumar          7.0
9        Kartik Aaryan          5.9
10        Varun Dhawan          6.1
11       Vicky Kaushal          8.2

In [8]:
df.loc[1]    # label-based: Returns the row with index label 1 (label-based selection)

Actor                 Salman Khan
Film              Tiger Zinda Hai
Year                         2017
Genre                      Action
BoxOffice_IMDb                565
IMDb_Rating                   6.0
Name: 1, dtype: object

In [9]:
df.iloc[1]   # Index-based: Returns the second row based on position (0-based indexing) => By position

Actor                 Salman Khan
Film              Tiger Zinda Hai
Year                         2017
Genre                      Action
BoxOffice_IMDb                565
IMDb_Rating                   6.0
Name: 1, dtype: object

In [10]:
df.loc[8, 'IMDb_Rating'] # Returns the IMDb_Rating value for the row with index label 8

np.float64(7.0)

In [11]:
df.iloc[8,5]

np.float64(7.0)

In [12]:
df.loc[0:2, ["Actor", "IMDb_Rating"]]

            Actor  IMDb_Rating
0  Shah Rukh Khan          7.2
1     Salman Khan          6.0
2      Aamir Khan          8.4

In [13]:
df.iloc[0:2,0:3]

            Actor             Film  Year
0  Shah Rukh Khan          Pathaan  2023
1     Salman Khan  Tiger Zinda Hai  2017

In [14]:
df.at[0, 'Actor']   # Returns the value in the 'Actor' column for the row with index label 0, And it is more optimise, and work on only one element

# there are also has "iat"

'Shah Rukh Khan'

In [15]:
df[df['IMDb_Rating']>6] # Filtering

,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [16]:
df[df['IMDb_Rating']>6]['Actor'] # Returns the names of actors whose IMDb_Rating is greater than 6

0         Shah Rukh Khan
2             Aamir Khan
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [18]:
df[(df['IMDb_Rating']>6) & (df['Year']>2018)]

,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [19]:
df[(df['IMDb_Rating']>6) | (df['Year']>2018)]

,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [ ]:
df.query("Year > 2019 and IMDb_Rating >6") # It gives a copy not view

            Actor     Film  Year   Genre  BoxOffice_IMDb  IMDb_Rating
0  Shah Rukh Khan  Pathaan  2023  Action            1050          7.2