In [47]:
import pandas as pd

df = pd.read_json(r"D:\Data-science\panda\File\DataCleaning_Preprocessing.json")
df

               name   age  ...                  email joining_date
0        Iman Datta  20.0  ...   iman.datta@gmail.com   2023-07-15
1       Ayesha Khan  21.0  ...  ayesha.khan@gmail.com   2022-11-02
2       Rahul Verma   NaN  ...  rahul.verma@gmail.com   2021-05-18
3       Neha Sharma  23.0  ...  neha.sharma@gmail.com   2020-09-10
4       Arjun Singh  25.0  ...                   None   2019-01-25
5       Priya Mehta  22.0  ...  priya.mehta@gmail.com         None
6        Sourav Das  24.0  ...   sourav.das@gmail.com   2023-03-12
7        Ritika Sen   NaN  ...   ritika.sen@gmail.com   2022-06-30
8       Ankit Yadav  26.0  ...  ankit.yadav@gmail.com   2021-12-05
9         Sneha Roy  21.0  ...                   None   2023-08-01
10      Mohit Gupta  28.0  ...  mohit.gupta@gmail.com   2018-04-19
11       Pooja Nair   NaN  ...   pooja.nair@gmail.com   2020-10-11
12   Rohan Malhotra  27.0  ...      rohan.m@gmail.com         None
13       Kavya Iyer  24.0  ...   kavya.iyer@gmail.com   2022-02-14
14  Aditya Kulkarni  29.0  ...     aditya.k@gmail.com   2017-07-07
15      Nisha Patel  23.0  ...  nisha.patel@gmail.com   2021-09-21
16   Aman Choudhary   NaN  ...       aman.c@gmail.com   2019-11-03
17       Tanya Bose  22.0  ...   tanya.bose@gmail.com         None
18    Deepak Mishra  31.0  ...                   None   2016-05-29
19      Riya Kapoor  20.0  ...  riya.kapoor@gmail.com   2024-01-10
20      Ayesha Khan  21.0  ...  ayesha.khan@gmail.com   2022-11-02
21       Tanya Bose  22.0  ...   tanya.bose@gmail.com         None
22   Rohan Malhotra  27.0  ...      rohan.m@gmail.com         None

[23 rows x 6 columns]

In [48]:
df.isnull()

     name    age   city  gender  email  joining_date
0   False  False  False   False  False         False
1   False  False  False   False  False         False
2   False   True  False   False  False         False
3   False  False   True   False  False         False
4   False  False  False   False   True         False
5   False  False  False   False  False          True
6   False  False  False   False  False         False
7   False   True  False   False  False         False
8   False  False  False   False  False         False
9   False  False  False   False   True         False
10  False  False  False   False  False         False
11  False   True  False   False  False         False
12  False  False  False   False  False          True
13  False  False  False   False  False         False
14  False  False   True   False  False         False
15  False  False  False   False  False         False
16  False   True  False   False  False         False
17  False  False  False   False  False          True
18  False  False  False   False   True         False
19  False  False  False   False  False         False
20  False  False  False   False  False         False
21  False  False  False   False  False          True
22  False  False  False   False  False          True

In [49]:
df.isnull().sum()

name            0
age             4
city            2
gender          0
email           3
joining_date    5
dtype: int64

In [50]:
df.dropna()

           name   age     city gender                  email joining_date
0    Iman Datta  20.0  Kolkata      M   iman.datta@gmail.com   2023-07-15
1   Ayesha Khan  21.0    Delhi      F  ayesha.khan@gmail.com   2022-11-02
6    Sourav Das  24.0  Kolkata      M   sourav.das@gmail.com   2023-03-12
8   Ankit Yadav  26.0    Noida      M  ankit.yadav@gmail.com   2021-12-05
10  Mohit Gupta  28.0   Jaipur      M  mohit.gupta@gmail.com   2018-04-19
13   Kavya Iyer  24.0  Chennai      F   kavya.iyer@gmail.com   2022-02-14
15  Nisha Patel  23.0    Surat      F  nisha.patel@gmail.com   2021-09-21
19  Riya Kapoor  20.0    Delhi      F  riya.kapoor@gmail.com   2024-01-10
20  Ayesha Khan  21.0    Delhi      F  ayesha.khan@gmail.com   2022-11-02

In [51]:
df.dropna(axis=1)

               name gender
0        Iman Datta      M
1       Ayesha Khan      F
2       Rahul Verma      M
3       Neha Sharma      F
4       Arjun Singh      M
5       Priya Mehta      F
6        Sourav Das      M
7        Ritika Sen      F
8       Ankit Yadav      M
9         Sneha Roy      F
10      Mohit Gupta      M
11       Pooja Nair      F
12   Rohan Malhotra      M
13       Kavya Iyer      F
14  Aditya Kulkarni      M
15      Nisha Patel      F
16   Aman Choudhary      M
17       Tanya Bose      F
18    Deepak Mishra      M
19      Riya Kapoor      F
20      Ayesha Khan      F
21       Tanya Bose      F
22   Rohan Malhotra      M

In [52]:
df.fillna(0)

               name   age  ...                  email joining_date
0        Iman Datta  20.0  ...   iman.datta@gmail.com   2023-07-15
1       Ayesha Khan  21.0  ...  ayesha.khan@gmail.com   2022-11-02
2       Rahul Verma   0.0  ...  rahul.verma@gmail.com   2021-05-18
3       Neha Sharma  23.0  ...  neha.sharma@gmail.com   2020-09-10
4       Arjun Singh  25.0  ...                      0   2019-01-25
5       Priya Mehta  22.0  ...  priya.mehta@gmail.com            0
6        Sourav Das  24.0  ...   sourav.das@gmail.com   2023-03-12
7        Ritika Sen   0.0  ...   ritika.sen@gmail.com   2022-06-30
8       Ankit Yadav  26.0  ...  ankit.yadav@gmail.com   2021-12-05
9         Sneha Roy  21.0  ...                      0   2023-08-01
10      Mohit Gupta  28.0  ...  mohit.gupta@gmail.com   2018-04-19
11       Pooja Nair   0.0  ...   pooja.nair@gmail.com   2020-10-11
12   Rohan Malhotra  27.0  ...      rohan.m@gmail.com            0
13       Kavya Iyer  24.0  ...   kavya.iyer@gmail.com   2022-02-14
14  Aditya Kulkarni  29.0  ...     aditya.k@gmail.com   2017-07-07
15      Nisha Patel  23.0  ...  nisha.patel@gmail.com   2021-09-21
16   Aman Choudhary   0.0  ...       aman.c@gmail.com   2019-11-03
17       Tanya Bose  22.0  ...   tanya.bose@gmail.com            0
18    Deepak Mishra  31.0  ...                      0   2016-05-29
19      Riya Kapoor  20.0  ...  riya.kapoor@gmail.com   2024-01-10
20      Ayesha Khan  21.0  ...  ayesha.khan@gmail.com   2022-11-02
21       Tanya Bose  22.0  ...   tanya.bose@gmail.com            0
22   Rohan Malhotra  27.0  ...      rohan.m@gmail.com            0

[23 rows x 6 columns]

In [53]:
# df["age"].fillna(df["age"].mean())

In [54]:
df.fillna(method="ffill") # forward fill

C:\Users\USER\AppData\Local\Temp\ipykernel_8412\2535960854.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill") # forward fill

               name   age  ...                  email joining_date
0        Iman Datta  20.0  ...   iman.datta@gmail.com   2023-07-15
1       Ayesha Khan  21.0  ...  ayesha.khan@gmail.com   2022-11-02
2       Rahul Verma  21.0  ...  rahul.verma@gmail.com   2021-05-18
3       Neha Sharma  23.0  ...  neha.sharma@gmail.com   2020-09-10
4       Arjun Singh  25.0  ...  neha.sharma@gmail.com   2019-01-25
5       Priya Mehta  22.0  ...  priya.mehta@gmail.com   2019-01-25
6        Sourav Das  24.0  ...   sourav.das@gmail.com   2023-03-12
7        Ritika Sen  24.0  ...   ritika.sen@gmail.com   2022-06-30
8       Ankit Yadav  26.0  ...  ankit.yadav@gmail.com   2021-12-05
9         Sneha Roy  21.0  ...  ankit.yadav@gmail.com   2023-08-01
10      Mohit Gupta  28.0  ...  mohit.gupta@gmail.com   2018-04-19
11       Pooja Nair  28.0  ...   pooja.nair@gmail.com   2020-10-11
12   Rohan Malhotra  27.0  ...      rohan.m@gmail.com   2020-10-11
13       Kavya Iyer  24.0  ...   kavya.iyer@gmail.com   2022-02-14
14  Aditya Kulkarni  29.0  ...     aditya.k@gmail.com   2017-07-07
15      Nisha Patel  23.0  ...  nisha.patel@gmail.com   2021-09-21
16   Aman Choudhary  23.0  ...       aman.c@gmail.com   2019-11-03
17       Tanya Bose  22.0  ...   tanya.bose@gmail.com   2019-11-03
18    Deepak Mishra  31.0  ...   tanya.bose@gmail.com   2016-05-29
19      Riya Kapoor  20.0  ...  riya.kapoor@gmail.com   2024-01-10
20      Ayesha Khan  21.0  ...  ayesha.khan@gmail.com   2022-11-02
21       Tanya Bose  22.0  ...   tanya.bose@gmail.com   2022-11-02
22   Rohan Malhotra  27.0  ...      rohan.m@gmail.com   2022-11-02

[23 rows x 6 columns]

In [55]:
df.bfill() # backward fill

               name   age  ...                  email joining_date
0        Iman Datta  20.0  ...   iman.datta@gmail.com   2023-07-15
1       Ayesha Khan  21.0  ...  ayesha.khan@gmail.com   2022-11-02
2       Rahul Verma  23.0  ...  rahul.verma@gmail.com   2021-05-18
3       Neha Sharma  23.0  ...  neha.sharma@gmail.com   2020-09-10
4       Arjun Singh  25.0  ...  priya.mehta@gmail.com   2019-01-25
5       Priya Mehta  22.0  ...  priya.mehta@gmail.com   2023-03-12
6        Sourav Das  24.0  ...   sourav.das@gmail.com   2023-03-12
7        Ritika Sen  26.0  ...   ritika.sen@gmail.com   2022-06-30
8       Ankit Yadav  26.0  ...  ankit.yadav@gmail.com   2021-12-05
9         Sneha Roy  21.0  ...  mohit.gupta@gmail.com   2023-08-01
10      Mohit Gupta  28.0  ...  mohit.gupta@gmail.com   2018-04-19
11       Pooja Nair  27.0  ...   pooja.nair@gmail.com   2020-10-11
12   Rohan Malhotra  27.0  ...      rohan.m@gmail.com   2022-02-14
13       Kavya Iyer  24.0  ...   kavya.iyer@gmail.com   2022-02-14
14  Aditya Kulkarni  29.0  ...     aditya.k@gmail.com   2017-07-07
15      Nisha Patel  23.0  ...  nisha.patel@gmail.com   2021-09-21
16   Aman Choudhary  22.0  ...       aman.c@gmail.com   2019-11-03
17       Tanya Bose  22.0  ...   tanya.bose@gmail.com   2016-05-29
18    Deepak Mishra  31.0  ...  riya.kapoor@gmail.com   2016-05-29
19      Riya Kapoor  20.0  ...  riya.kapoor@gmail.com   2024-01-10
20      Ayesha Khan  21.0  ...  ayesha.khan@gmail.com   2022-11-02
21       Tanya Bose  22.0  ...   tanya.bose@gmail.com         None
22   Rohan Malhotra  27.0  ...      rohan.m@gmail.com         None

[23 rows x 6 columns]

In [60]:
df.duplicated(["email"])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20     True
21     True
22     True
dtype: bool

In [56]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21     True
22     True
dtype: bool

In [ ]:
df.drop_duplicates() # It removes duplicate data

               name   age  ...                  email joining_date
0        Iman Datta  20.0  ...   iman.datta@gmail.com   2023-07-15
1       Ayesha Khan  21.0  ...  ayesha.khan@gmail.com   2022-11-02
2       Rahul Verma   NaN  ...  rahul.verma@gmail.com   2021-05-18
3       Neha Sharma  23.0  ...  neha.sharma@gmail.com   2020-09-10
4       Arjun Singh  25.0  ...                   None   2019-01-25
5       Priya Mehta  22.0  ...  priya.mehta@gmail.com         None
6        Sourav Das  24.0  ...   sourav.das@gmail.com   2023-03-12
7        Ritika Sen   NaN  ...   ritika.sen@gmail.com   2022-06-30
8       Ankit Yadav  26.0  ...  ankit.yadav@gmail.com   2021-12-05
9         Sneha Roy  21.0  ...                   None   2023-08-01
10      Mohit Gupta  28.0  ...  mohit.gupta@gmail.com   2018-04-19
11       Pooja Nair   NaN  ...   pooja.nair@gmail.com   2020-10-11
12   Rohan Malhotra  27.0  ...      rohan.m@gmail.com         None
13       Kavya Iyer  24.0  ...   kavya.iyer@gmail.com   2022-02-14
14  Aditya Kulkarni  29.0  ...     aditya.k@gmail.com   2017-07-07
15      Nisha Patel  23.0  ...  nisha.patel@gmail.com   2021-09-21
16   Aman Choudhary   NaN  ...       aman.c@gmail.com   2019-11-03
17       Tanya Bose  22.0  ...   tanya.bose@gmail.com         None
18    Deepak Mishra  31.0  ...                   None   2016-05-29
19      Riya Kapoor  20.0  ...  riya.kapoor@gmail.com   2024-01-10

[20 rows x 6 columns]