In [2]:
import pandas as pd

df = pd.read_json(r"D:\Data-science\panda\File\DataCleaning_Preprocessing.json")
df

,name,age,city,gender,email,joining_date
0,Iman Datta,20.0,Kolkata,M,iman.datta@gmail.com,2023-07-15
1,Ayesha Khan,21.0,Delhi,F,ayesha.khan@gmail.com,2022-11-02
2,Rahul Verma,NaN,Mumbai,M,rahul.verma@gmail.com,2021-05-18
3,Neha Sharma,23.0,None,F,neha.sharma@gmail.com,2020-09-10
4,Arjun Singh,25.0,Chandigarh,M,None,2019-01-25
5,Priya Mehta,22.0,Ahmedabad,F,priya.mehta@gmail.com,None
6,Sourav Das,24.0,Kolkata,M,sourav.das@gmail.com,2023-03-12
7,Ritika Sen,NaN,Pune,F,ritika.sen@gmail.com,2022-06-30
8,Ankit Yadav,26.0,Noida,M,ankit.yadav@gmail.com,2021-12-05
9,Sneha Roy,21.0,Kolkata,F,None,2023-08-01
10,Mohit Gupta,28.0,Jaipur,M,mohit.gupta@gmail.com,2018-04-19
11,Pooja Nair,NaN,Kochi,F,pooja.nair@gmail.com,2020-10-11
12,Rohan Malhotra,27.0,Gurgaon,M,rohan.m@gmail.com,None
13,Kavya Iyer,24.0,Chennai,F,kavya.iyer@gmail.com,2022-02-14
14,Aditya Kulkarni,29.0,None,M,aditya.k@gmail.com,2017-07-07
15,Nisha Patel,23.0,Surat,F,nisha.patel@gmail.com,2021-09-21
16,Aman Choudhary,NaN,Bhopal,M,aman.c@gmail.com,2019-11-03
17,Tanya Bose,22.0,Kolkata,F,tanya.bose@gmail.com,None
18,Deepak Mishra,31.0,Lucknow,M,None,2016-05-29
19,Riya Kapoor,20.0,Delhi,F,riya.kapoor@gmail.com,2024-01-10
20,Ayesha Khan,21.0,Delhi,F,ayesha.khan@gmail.com,2022-11-02
21,Tanya Bose,22.0,Kolkata,F,tanya.bose@gmail.com,None
22,Rohan Malhotra,27.0,Gurgaon,M,rohan.m@gmail.com,None

In [3]:
df.isnull()

     name    age   city  gender  email  joining_date
0   False  False  False   False  False         False
1   False  False  False   False  False         False
2   False   True  False   False  False         False
3   False  False   True   False  False         False
4   False  False  False   False   True         False
5   False  False  False   False  False          True
6   False  False  False   False  False         False
7   False   True  False   False  False         False
8   False  False  False   False  False         False
9   False  False  False   False   True         False
10  False  False  False   False  False         False
11  False   True  False   False  False         False
12  False  False  False   False  False          True
13  False  False  False   False  False         False
14  False  False   True   False  False         False
15  False  False  False   False  False         False
16  False   True  False   False  False         False
17  False  False  False   False  False          True
18  False  False  False   False   True         False
19  False  False  False   False  False         False
20  False  False  False   False  False         False
21  False  False  False   False  False          True
22  False  False  False   False  False          True

In [4]:
df.isnull().sum()

name            0
age             4
city            2
gender          0
email           3
joining_date    5
dtype: int64

In [5]:
df.dropna()

           name   age     city gender                  email joining_date
0    Iman Datta  20.0  Kolkata      M   iman.datta@gmail.com   2023-07-15
1   Ayesha Khan  21.0    Delhi      F  ayesha.khan@gmail.com   2022-11-02
6    Sourav Das  24.0  Kolkata      M   sourav.das@gmail.com   2023-03-12
8   Ankit Yadav  26.0    Noida      M  ankit.yadav@gmail.com   2021-12-05
10  Mohit Gupta  28.0   Jaipur      M  mohit.gupta@gmail.com   2018-04-19
13   Kavya Iyer  24.0  Chennai      F   kavya.iyer@gmail.com   2022-02-14
15  Nisha Patel  23.0    Surat      F  nisha.patel@gmail.com   2021-09-21
19  Riya Kapoor  20.0    Delhi      F  riya.kapoor@gmail.com   2024-01-10
20  Ayesha Khan  21.0    Delhi      F  ayesha.khan@gmail.com   2022-11-02

In [6]:
df.dropna(axis=1)

               name gender
0        Iman Datta      M
1       Ayesha Khan      F
2       Rahul Verma      M
3       Neha Sharma      F
4       Arjun Singh      M
5       Priya Mehta      F
6        Sourav Das      M
7        Ritika Sen      F
8       Ankit Yadav      M
9         Sneha Roy      F
10      Mohit Gupta      M
11       Pooja Nair      F
12   Rohan Malhotra      M
13       Kavya Iyer      F
14  Aditya Kulkarni      M
15      Nisha Patel      F
16   Aman Choudhary      M
17       Tanya Bose      F
18    Deepak Mishra      M
19      Riya Kapoor      F
20      Ayesha Khan      F
21       Tanya Bose      F
22   Rohan Malhotra      M

In [7]:
df.fillna(0)

,name,age,city,gender,email,joining_date
0,Iman Datta,20.0,Kolkata,M,iman.datta@gmail.com,2023-07-15
1,Ayesha Khan,21.0,Delhi,F,ayesha.khan@gmail.com,2022-11-02
2,Rahul Verma,0.0,Mumbai,M,rahul.verma@gmail.com,2021-05-18
3,Neha Sharma,23.0,0,F,neha.sharma@gmail.com,2020-09-10
4,Arjun Singh,25.0,Chandigarh,M,0,2019-01-25
5,Priya Mehta,22.0,Ahmedabad,F,priya.mehta@gmail.com,0
6,Sourav Das,24.0,Kolkata,M,sourav.das@gmail.com,2023-03-12
7,Ritika Sen,0.0,Pune,F,ritika.sen@gmail.com,2022-06-30
8,Ankit Yadav,26.0,Noida,M,ankit.yadav@gmail.com,2021-12-05
9,Sneha Roy,21.0,Kolkata,F,0,2023-08-01
10,Mohit Gupta,28.0,Jaipur,M,mohit.gupta@gmail.com,2018-04-19
11,Pooja Nair,0.0,Kochi,F,pooja.nair@gmail.com,2020-10-11
12,Rohan Malhotra,27.0,Gurgaon,M,rohan.m@gmail.com,0
13,Kavya Iyer,24.0,Chennai,F,kavya.iyer@gmail.com,2022-02-14
14,Aditya Kulkarni,29.0,0,M,aditya.k@gmail.com,2017-07-07
15,Nisha Patel,23.0,Surat,F,nisha.patel@gmail.com,2021-09-21
16,Aman Choudhary,0.0,Bhopal,M,aman.c@gmail.com,2019-11-03
17,Tanya Bose,22.0,Kolkata,F,tanya.bose@gmail.com,0
18,Deepak Mishra,31.0,Lucknow,M,0,2016-05-29
19,Riya Kapoor,20.0,Delhi,F,riya.kapoor@gmail.com,2024-01-10
20,Ayesha Khan,21.0,Delhi,F,ayesha.khan@gmail.com,2022-11-02
21,Tanya Bose,22.0,Kolkata,F,tanya.bose@gmail.com,0
22,Rohan Malhotra,27.0,Gurgaon,M,rohan.m@gmail.com,0

In [8]:
# df["age"].fillna(df["age"].mean())

In [9]:
df.fillna(method="ffill") # forward fill

C:\Users\USER\AppData\Local\Temp\ipykernel_27400\2535960854.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill") # forward fill

,name,age,city,gender,email,joining_date
0,Iman Datta,20.0,Kolkata,M,iman.datta@gmail.com,2023-07-15
1,Ayesha Khan,21.0,Delhi,F,ayesha.khan@gmail.com,2022-11-02
2,Rahul Verma,21.0,Mumbai,M,rahul.verma@gmail.com,2021-05-18
3,Neha Sharma,23.0,Mumbai,F,neha.sharma@gmail.com,2020-09-10
4,Arjun Singh,25.0,Chandigarh,M,neha.sharma@gmail.com,2019-01-25
5,Priya Mehta,22.0,Ahmedabad,F,priya.mehta@gmail.com,2019-01-25
6,Sourav Das,24.0,Kolkata,M,sourav.das@gmail.com,2023-03-12
7,Ritika Sen,24.0,Pune,F,ritika.sen@gmail.com,2022-06-30
8,Ankit Yadav,26.0,Noida,M,ankit.yadav@gmail.com,2021-12-05
9,Sneha Roy,21.0,Kolkata,F,ankit.yadav@gmail.com,2023-08-01
10,Mohit Gupta,28.0,Jaipur,M,mohit.gupta@gmail.com,2018-04-19
11,Pooja Nair,28.0,Kochi,F,pooja.nair@gmail.com,2020-10-11
12,Rohan Malhotra,27.0,Gurgaon,M,rohan.m@gmail.com,2020-10-11
13,Kavya Iyer,24.0,Chennai,F,kavya.iyer@gmail.com,2022-02-14
14,Aditya Kulkarni,29.0,Chennai,M,aditya.k@gmail.com,2017-07-07
15,Nisha Patel,23.0,Surat,F,nisha.patel@gmail.com,2021-09-21
16,Aman Choudhary,23.0,Bhopal,M,aman.c@gmail.com,2019-11-03
17,Tanya Bose,22.0,Kolkata,F,tanya.bose@gmail.com,2019-11-03
18,Deepak Mishra,31.0,Lucknow,M,tanya.bose@gmail.com,2016-05-29
19,Riya Kapoor,20.0,Delhi,F,riya.kapoor@gmail.com,2024-01-10
20,Ayesha Khan,21.0,Delhi,F,ayesha.khan@gmail.com,2022-11-02
21,Tanya Bose,22.0,Kolkata,F,tanya.bose@gmail.com,2022-11-02
22,Rohan Malhotra,27.0,Gurgaon,M,rohan.m@gmail.com,2022-11-02

In [10]:
df.bfill() # backward fill

,name,age,city,gender,email,joining_date
0,Iman Datta,20.0,Kolkata,M,iman.datta@gmail.com,2023-07-15
1,Ayesha Khan,21.0,Delhi,F,ayesha.khan@gmail.com,2022-11-02
2,Rahul Verma,23.0,Mumbai,M,rahul.verma@gmail.com,2021-05-18
3,Neha Sharma,23.0,Chandigarh,F,neha.sharma@gmail.com,2020-09-10
4,Arjun Singh,25.0,Chandigarh,M,priya.mehta@gmail.com,2019-01-25
5,Priya Mehta,22.0,Ahmedabad,F,priya.mehta@gmail.com,2023-03-12
6,Sourav Das,24.0,Kolkata,M,sourav.das@gmail.com,2023-03-12
7,Ritika Sen,26.0,Pune,F,ritika.sen@gmail.com,2022-06-30
8,Ankit Yadav,26.0,Noida,M,ankit.yadav@gmail.com,2021-12-05
9,Sneha Roy,21.0,Kolkata,F,mohit.gupta@gmail.com,2023-08-01
10,Mohit Gupta,28.0,Jaipur,M,mohit.gupta@gmail.com,2018-04-19
11,Pooja Nair,27.0,Kochi,F,pooja.nair@gmail.com,2020-10-11
12,Rohan Malhotra,27.0,Gurgaon,M,rohan.m@gmail.com,2022-02-14
13,Kavya Iyer,24.0,Chennai,F,kavya.iyer@gmail.com,2022-02-14
14,Aditya Kulkarni,29.0,Surat,M,aditya.k@gmail.com,2017-07-07
15,Nisha Patel,23.0,Surat,F,nisha.patel@gmail.com,2021-09-21
16,Aman Choudhary,22.0,Bhopal,M,aman.c@gmail.com,2019-11-03
17,Tanya Bose,22.0,Kolkata,F,tanya.bose@gmail.com,2016-05-29
18,Deepak Mishra,31.0,Lucknow,M,riya.kapoor@gmail.com,2016-05-29
19,Riya Kapoor,20.0,Delhi,F,riya.kapoor@gmail.com,2024-01-10
20,Ayesha Khan,21.0,Delhi,F,ayesha.khan@gmail.com,2022-11-02
21,Tanya Bose,22.0,Kolkata,F,tanya.bose@gmail.com,None
22,Rohan Malhotra,27.0,Gurgaon,M,rohan.m@gmail.com,None

In [11]:
df.duplicated(["email"])

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
20     True
21     True
22     True
dtype: bool

In [12]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20     True
21     True
22     True
dtype: bool

In [13]:
df.drop_duplicates() # It removes duplicate data

,name,age,city,gender,email,joining_date
0,Iman Datta,20.0,Kolkata,M,iman.datta@gmail.com,2023-07-15
1,Ayesha Khan,21.0,Delhi,F,ayesha.khan@gmail.com,2022-11-02
2,Rahul Verma,NaN,Mumbai,M,rahul.verma@gmail.com,2021-05-18
3,Neha Sharma,23.0,None,F,neha.sharma@gmail.com,2020-09-10
4,Arjun Singh,25.0,Chandigarh,M,None,2019-01-25
5,Priya Mehta,22.0,Ahmedabad,F,priya.mehta@gmail.com,None
6,Sourav Das,24.0,Kolkata,M,sourav.das@gmail.com,2023-03-12
7,Ritika Sen,NaN,Pune,F,ritika.sen@gmail.com,2022-06-30
8,Ankit Yadav,26.0,Noida,M,ankit.yadav@gmail.com,2021-12-05
9,Sneha Roy,21.0,Kolkata,F,None,2023-08-01
10,Mohit Gupta,28.0,Jaipur,M,mohit.gupta@gmail.com,2018-04-19
11,Pooja Nair,NaN,Kochi,F,pooja.nair@gmail.com,2020-10-11
12,Rohan Malhotra,27.0,Gurgaon,M,rohan.m@gmail.com,None
13,Kavya Iyer,24.0,Chennai,F,kavya.iyer@gmail.com,2022-02-14
14,Aditya Kulkarni,29.0,None,M,aditya.k@gmail.com,2017-07-07
15,Nisha Patel,23.0,Surat,F,nisha.patel@gmail.com,2021-09-21
16,Aman Choudhary,NaN,Bhopal,M,aman.c@gmail.com,2019-11-03
17,Tanya Bose,22.0,Kolkata,F,tanya.bose@gmail.com,None
18,Deepak Mishra,31.0,Lucknow,M,None,2016-05-29
19,Riya Kapoor,20.0,Delhi,F,riya.kapoor@gmail.com,2024-01-10

In [14]:
df["name"].str.lower()

0          iman datta
1         ayesha khan
2         rahul verma
3         neha sharma
4         arjun singh
5         priya mehta
6          sourav das
7          ritika sen
8         ankit yadav
9           sneha roy
10        mohit gupta
11         pooja nair
12     rohan malhotra
13         kavya iyer
14    aditya kulkarni
15        nisha patel
16     aman choudhary
17         tanya bose
18      deepak mishra
19        riya kapoor
20        ayesha khan
21         tanya bose
22     rohan malhotra
Name: name, dtype: object

In [17]:
df["city"].str.contains("delhi", case=False) # Checks if "delhi" is the in the city name, case insensitive.

0     False
1      True
2     False
3      None
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14     None
15    False
16    False
17    False
18    False
19     True
20     True
21    False
22    False
Name: city, dtype: object

In [18]:
df["email"].str.split('@')

0      [iman.datta, gmail.com]
1     [ayesha.khan, gmail.com]
2     [rahul.verma, gmail.com]
3     [neha.sharma, gmail.com]
4                         None
5     [priya.mehta, gmail.com]
6      [sourav.das, gmail.com]
7      [ritika.sen, gmail.com]
8     [ankit.yadav, gmail.com]
9                         None
10    [mohit.gupta, gmail.com]
11     [pooja.nair, gmail.com]
12        [rohan.m, gmail.com]
13     [kavya.iyer, gmail.com]
14       [aditya.k, gmail.com]
15    [nisha.patel, gmail.com]
16         [aman.c, gmail.com]
17     [tanya.bose, gmail.com]
18                        None
19    [riya.kapoor, gmail.com]
20    [ayesha.khan, gmail.com]
21     [tanya.bose, gmail.com]
22        [rohan.m, gmail.com]
Name: email, dtype: object

In [19]:
df2 = df.dropna().copy()

In [22]:
df2["age"] = df2["age"].astype(int)
df2

           name  age     city gender                  email joining_date
0    Iman Datta   20  Kolkata      M   iman.datta@gmail.com   2023-07-15
1   Ayesha Khan   21    Delhi      F  ayesha.khan@gmail.com   2022-11-02
6    Sourav Das   24  Kolkata      M   sourav.das@gmail.com   2023-03-12
8   Ankit Yadav   26    Noida      M  ankit.yadav@gmail.com   2021-12-05
10  Mohit Gupta   28   Jaipur      M  mohit.gupta@gmail.com   2018-04-19
13   Kavya Iyer   24  Chennai      F   kavya.iyer@gmail.com   2022-02-14
15  Nisha Patel   23    Surat      F  nisha.patel@gmail.com   2021-09-21
19  Riya Kapoor   20    Delhi      F  riya.kapoor@gmail.com   2024-01-10
20  Ayesha Khan   21    Delhi      F  ayesha.khan@gmail.com   2022-11-02

In [24]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 20
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          9 non-null      object
 1   age           9 non-null      int64
 2   city          9 non-null      object
 3   gender        9 non-null      object
 4   email         9 non-null      object
 5   joining_date  9 non-null      object
dtypes: int64(1), object(5)
memory usage: 504.0+ bytes

In [26]:
df2["age group"] = df2["age"].apply(lambda x: "Adult" if x >=18 else "Minor")
df2

,name,age,city,gender,email,joining_date,age group
0,Iman Datta,20,Kolkata,M,iman.datta@gmail.com,2023-07-15,Adult
1,Ayesha Khan,21,Delhi,F,ayesha.khan@gmail.com,2022-11-02,Adult
6,Sourav Das,24,Kolkata,M,sourav.das@gmail.com,2023-03-12,Adult
8,Ankit Yadav,26,Noida,M,ankit.yadav@gmail.com,2021-12-05,Adult
10,Mohit Gupta,28,Jaipur,M,mohit.gupta@gmail.com,2018-04-19,Adult
13,Kavya Iyer,24,Chennai,F,kavya.iyer@gmail.com,2022-02-14,Adult
15,Nisha Patel,23,Surat,F,nisha.patel@gmail.com,2021-09-21,Adult
19,Riya Kapoor,20,Delhi,F,riya.kapoor@gmail.com,2024-01-10,Adult
20,Ayesha Khan,21,Delhi,F,ayesha.khan@gmail.com,2022-11-02,Adult

In [30]:
def isMinor(x):
    return "Adult" if x >= 18 else "Minor"
df2["age group"] = df2["age"].apply(isMinor)
df2

,name,age,city,gender,email,joining_date,age group
0,Iman Datta,20,Kolkata,M,iman.datta@gmail.com,2023-07-15,Adult
1,Ayesha Khan,21,Delhi,F,ayesha.khan@gmail.com,2022-11-02,Adult
6,Sourav Das,24,Kolkata,M,sourav.das@gmail.com,2023-03-12,Adult
8,Ankit Yadav,26,Noida,M,ankit.yadav@gmail.com,2021-12-05,Adult
10,Mohit Gupta,28,Jaipur,M,mohit.gupta@gmail.com,2018-04-19,Adult
13,Kavya Iyer,24,Chennai,F,kavya.iyer@gmail.com,2022-02-14,Adult
15,Nisha Patel,23,Surat,F,nisha.patel@gmail.com,2021-09-21,Adult
19,Riya Kapoor,20,Delhi,F,riya.kapoor@gmail.com,2024-01-10,Adult
20,Ayesha Khan,21,Delhi,F,ayesha.khan@gmail.com,2022-11-02,Adult

In [31]:
gender_map = {"M" : "Male", "F" : "Female", "O" : "Other"}
df2["gender"] = df2["gender"].map(gender_map)
df2

,name,age,city,gender,email,joining_date,age group
0,Iman Datta,20,Kolkata,Male,iman.datta@gmail.com,2023-07-15,Adult
1,Ayesha Khan,21,Delhi,Female,ayesha.khan@gmail.com,2022-11-02,Adult
6,Sourav Das,24,Kolkata,Male,sourav.das@gmail.com,2023-03-12,Adult
8,Ankit Yadav,26,Noida,Male,ankit.yadav@gmail.com,2021-12-05,Adult
10,Mohit Gupta,28,Jaipur,Male,mohit.gupta@gmail.com,2018-04-19,Adult
13,Kavya Iyer,24,Chennai,Female,kavya.iyer@gmail.com,2022-02-14,Adult
15,Nisha Patel,23,Surat,Female,nisha.patel@gmail.com,2021-09-21,Adult
19,Riya Kapoor,20,Delhi,Female,riya.kapoor@gmail.com,2024-01-10,Adult
20,Ayesha Khan,21,Delhi,Female,ayesha.khan@gmail.com,2022-11-02,Adult