In [2]:
import pandas as pd

df = pd.read_json(r"D:\Data-science\panda\File\actors.json")
df

,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [3]:
df.sort_values("Year")

,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [4]:
df2 = df.sort_values(["Year","IMDb_Rating"]).copy()
df2

,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [5]:
df2.sort_index()

,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [6]:
df2.reset_index()

,index,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating
0,2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,7,Hrithik Roshan,War,2019,Action,475,6.5
7,8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [7]:
df2.reset_index(drop=True)

,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [8]:
df2.reset_index(drop=True, inplace=True)

In [9]:
df2

,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [10]:
df2["Rank"] = df2["IMDb_Rating"].rank()
df2

,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0
6,Hrithik Roshan,War,2019,Action,475,6.5,5.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0

In [11]:
df2["Rank"] = df2["IMDb_Rating"].rank(ascending=False, method="dense")
df2

,Actor,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating,Rank
0,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
6,Hrithik Roshan,War,2019,Action,475,6.5,7.0
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [12]:
df = df[["Film","Year", "Genre", "BoxOffice_IMDb", "IMDb_Rating"]] # Column re-order
df

,Film,Year,Genre,BoxOffice_IMDb,IMDb_Rating
0,Pathaan,2023,Action,1050,7.2
1,Tiger Zinda Hai,2017,Action,565,6.0
2,Dangal,2016,Biography,2024,8.4
3,Brahmastra,2022,Fantasy,431,5.6
4,Padmaavat,2018,Historical,585,7.0
5,Andhadhun,2018,Thriller,111,8.3
6,Stree,2018,Horror Comedy,180,7.5
7,War,2019,Action,475,6.5
8,Good Newwz,2019,Comedy,318,7.0
9,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Uri: The Surgical Strike,2019,Action,342,8.2

In [17]:
cols = ["Year"] + [col for col in df.columns if col != "Year"] # Column => year push it to front
df = df[cols]
df

,Year,Film,Genre,BoxOffice_IMDb,IMDb_Rating
0,2023,Pathaan,Action,1050,7.2
1,2017,Tiger Zinda Hai,Action,565,6.0
2,2016,Dangal,Biography,2024,8.4
3,2022,Brahmastra,Fantasy,431,5.6
4,2018,Padmaavat,Historical,585,7.0
5,2018,Andhadhun,Thriller,111,8.3
6,2018,Stree,Horror Comedy,180,7.5
7,2019,War,Action,475,6.5
8,2019,Good Newwz,Comedy,318,7.0
9,2022,Bhool Bhulaiyaa 2,Horror Comedy,266,5.9
10,2017,Badrinath Ki Dulhania,Romantic Comedy,201,6.1
11,2019,Uri: The Surgical Strike,Action,342,8.2