In [1]:
import pandas as pd

df = pd.read_csv(r"D:\Data-science\panda\File\06_melt_pivort.csv")
df

      Name  Math  Science  English
0     Amit    78       82       74
1     Riya    85       88       90
2    Rahul    67       72       70
3    Sneha    92       89       94
4    Arjun    74       76       71
5     Neha    81       85       83
6    Vikas    69       65       68
7    Pooja    88       91       87
8    Ankit    73       70       75
9    Kavya    90       93       89
10   Rohit    64       66       62
11   Nisha    79       82       80
12   Suman    71       74       73
13  Aditya    86       84       88
14   Meera    91       90       92
15   Kunal    68       71       69
16    Isha    84       87       85
17  Deepak    75       78       76
18   Tanvi    89       92       90
19  Saurav    66       64       67
20   Priya    87       85       88
21  Manish    72       70       74
22  Ayesha    93       95       94
23   Harsh    77       79       78
24  Simran    82       84       81

In [18]:
df2 = df.melt(id_vars=["Name"], #  Columns to keep fixed
            value_vars=["Math", "Science", "English"], # Columns to unpivot
            var_name="Subject", # Name of the new column for subjects
            value_name="Score").copy().sort_values(["Name"]) # Name of the new column for values

df2

      Name  Subject  Score
63  Aditya  English     88
38  Aditya  Science     84
13  Aditya     Math     86
0     Amit     Math     78
50    Amit  English     74
..     ...      ...    ...
68   Tanvi  English     90
18   Tanvi     Math     89
31   Vikas  Science     65
6    Vikas     Math     69
56   Vikas  English     68

[75 rows x 3 columns]

In [ ]:
df2.pivot(index=["Name"], columns=["Subject"], values=["Score"]) # Convert long format back to wide format (subjects as columns)

          Score
Subject English Math Science
Name
Aditya       88   86      84
Amit         74   78      82
Ankit        75   73      70
Arjun        71   74      76
Ayesha       94   93      95
Deepak       76   75      78
Harsh        78   77      79
Isha         85   84      87
Kavya        89   90      93
Kunal        69   68      71
Manish       74   72      70
Meera        92   91      90
Neha         83   81      85
Nisha        80   79      82
Pooja        87   88      91
Priya        88   87      85
Rahul        70   67      72
Riya         90   85      88
Rohit        62   64      66
Saurav       67   66      64
Simran       81   82      84
Sneha        94   92      89
Suman        73   71      74
Tanvi        90   89      92
Vikas        68   69      65